### ISSUE TITLE
Error: Cannot find module '../lib/tailwindConfigUtils'

### ISSUE THREAD

**Issue by KubaJastrz** [rogden/tailwind-config-viewer#7]
I found a regression (cli works on version 1.0.0).

tailwind-config-viewer: v1.1.0
os: windows 10

```
$ npx tailwind-config-viewer
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '../lib/tailwindConfigUtils'
Require stack:
- <redacted>\my-project\node_modules\tailwind-config-viewer\server\index.js
- <redacted>\my-project\node_modules\tailwind-config-viewer\cli\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (<redacted>\my-project\node_modules\tailwind-config-viewer\server\index.js:6:46)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '<redacted>\\my-project\\node_modules\\tailwind-config-viewer\\server\\index.js',
    '<redacted>\\my-project\\node_modules\\tailwind-config-viewer\\cli\\index.js'
  ]
}
```

**Comment by rogden** [comment]
You are awesome. Thanks for reporting! Fixing now...

**Comment by rogden** [comment]
@KubaJastrz Should be fixed now in 1.1.1. Thanks 🙏 again!

**Comment by KubaJastrz** [comment]
@rogden Can confirm, it is working now! Thanks for quick fix.
